# Generated by Django 5.2.7 on 2025-10-29 06:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('kind', models.CharField(choices=[('video', 'Video'), ('text', 'Text / Lecture'), ('pdf', 'PDF'), ('doc', 'Word (DOC/DOCX)'), ('test', 'Test')], default='video', max_length=10)),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('text', models.TextField()),
                ('qtype', models.CharField(choices=[('sc', 'Single choice'), ('mc', 'Multiple choice'), ('txt', 'Text (manual grade)')], default='sc', max_length=3)),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/')),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TorrensAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('list_answer', models.JSONField(blank=True, null=True)),
                ('drawing_image', models.ImageField(blank=True, null=True, upload_to='torrens/ans/')),
                ('score', models.FloatField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TorrensTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('prompt', models.TextField(help_text="Topshiriq matni (ko'rsatma)")),
                ('response_type', models.CharField(choices=[('text', 'Matn yozish'), ('list', "G'oyalar ro'yxati"), ('drawing', 'Rasm/chizma')], default='text', max_length=20)),
                ('hint', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='torrens/ref/')),
                ('allow_text', models.BooleanField(default=True)),
                ('allow_images', models.BooleanField(default=True)),
                ('max_images', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='ui_category_slug_cdac51_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='slides/')),
                ('cta_primary_text', models.CharField(blank=True, default='Batafsil', max_length=40)),
                ('cta_primary_url', models.CharField(blank=True, default='#', max_length=200)),
                ('cta_secondary_text', models.CharField(blank=True, default='Hoziroq qo‘shiling', max_length=40)),
                ('cta_secondary_url', models.CharField(blank=True, default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'order'], name='ui_homepage_is_acti_5a0d5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('short_desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='ui.category')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='ui.instructor')),
            ],
            options={
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('DC', 'Dublin Core'), ('MARC21', 'MARC 21')], default='DC', max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='library/')),
                ('link', models.URLField(blank=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='library/thumbs/')),
                ('dc_creator', models.CharField(blank=True, max_length=500)),
                ('dc_date', models.CharField(blank=True, max_length=50)),
                ('dc_format', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'is_published'], name='ui_libraryi_created_eaa9fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ui.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='0 = cheksiz vaqt')),
                ('pass_percent', models.PositiveIntegerField(default=0, help_text='0 = pass talabi yo‘q')),
                ('attempts_limit', models.PositiveIntegerField(default=0, help_text='0 = cheksiz urinish')),
                ('limit_questions', models.PositiveIntegerField(blank=True, help_text='Nechta savol berilsin (bo‘sh – hammasi).', null=True)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_choices', models.BooleanField(default=True)),
                ('advice_mid_min', models.PositiveSmallIntegerField(default=50)),
                ('advice_high_min', models.PositiveSmallIntegerField(default=80)),
                ('advice_low', models.TextField(blank=True, default='Natijangiz past. Darsni qayta ko‘rib chiqing, qisqa konspekt tuzing va ko‘proq amaliy mashq bajaring.')),
                ('advice_mid', models.TextField(blank=True, default='Yaxshi! Endi murakkabroq misollarni bajaring va qo‘shimcha vazifalar bilan mustahkamlang.')),
                ('advice_high', models.TextField(blank=True, default='A’lo! Keyingi modulga o‘ting va chuqurlashtirilgan topshiriqlarni sinab ko‘ring.')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='ui.lesson')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ('lesson',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ui.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('points_total', models.FloatField(default=0)),
                ('points_gained', models.FloatField(default=0)),
                ('percent', models.FloatField(default=0)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('advice_shown', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='ui.lesson')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ui.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ui.course')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ui.section'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['is_published', 'order'], name='ui_testimon_is_publ_ef2aff_idx')],
            },
        ),
        migrations.CreateModel(
            name='TorrensAnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='torrens/ans_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ui.torrensanswer')),
            ],
        ),
        migrations.CreateModel(
            name='TorrensSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Jarayonda'), ('finished', 'Yakunlangan'), ('graded', 'Baholangan')], default='draft', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrens_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddField(
            model_name='torrensanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ui.torrenssubmission'),
        ),
        migrations.AddField(
            model_name='torrensanswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ui.torrenstask'),
        ),
        migrations.CreateModel(
            name='TorrensTaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='torrens/task_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='ui.torrenstask')),
            ],
            options={
                'verbose_name': 'Torrens topshiriq rasmi',
                'verbose_name_plural': 'Torrens topshiriq rasmlari',
            },
        ),
        migrations.CreateModel(
            name='TorrensTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 = cheklanmagan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['slug'], name='ui_torrenst_slug_3629b4_idx'), models.Index(fields=['-created_at'], name='ui_torrenst_created_398041_idx')],
            },
        ),
        migrations.AddField(
            model_name='torrenstask',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ui.torrenstest'),
        ),
        migrations.AddField(
            model_name='torrenssubmission',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ui.torrenstest'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='ui_course_slug_cf66bd_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='ui_course_created_d81ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='ui_course_is_feat_0f37ea_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='ui_question_quiz_id_a0bb3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-created_at'], name='ui_quizatte_user_id_7a5d89_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'order'], name='ui_section_course__0e0e53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['section', 'order'], name='ui_lesson_section_7b2b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'order')},
        ),
        migrations.AddIndex(
            model_name='torrensanswer',
            index=models.Index(fields=['submission', 'task'], name='ui_torrensa_submiss_70078b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='torrensanswer',
            unique_together={('submission', 'task')},
        ),
        migrations.AddIndex(
            model_name='torrenstask',
            index=models.Index(fields=['test', 'order'], name='ui_torrenst_test_id_016152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='torrenstask',
            unique_together={('test', 'order')},
        ),
        migrations.AddIndex(
            model_name='torrenssubmission',
            index=models.Index(fields=['test', 'user', '-started_at'], name='ui_torrenss_test_id_b717e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='torrenssubmission',
            unique_together={('test', 'user', 'finished_at')},
        ),
    ]
